"""added a phone-number column

Revision ID: 0a914f103f83
Revises: f6514318e5b1
Create Date: 2026-01-05 13:12:40.929736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a914f103f83'
down_revision: Union[str, Sequence[str], None] = 'f6514318e5b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('phone_number', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'Users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users', type_='unique')
    op.drop_column('Users', 'phone_number')
    # ### end Alembic commands ###
