"""added the remaining changes using autogenerate command

Revision ID: f6514318e5b1
Revises: 609a924654ab
Create Date: 2026-01-05 13:09:47.801724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6514318e5b1'
down_revision: Union[str, Sequence[str], None] = '609a924654ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Votes',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.Integer(), nullable=False),
    sa.Column('upvote', sa.Boolean(), nullable=True),
    sa.Column('downvote', sa.Boolean(), nullable=True),
    sa.CheckConstraint('NOT (upvote AND downvote)', name='check_not_both_true'),
    sa.ForeignKeyConstraint(['post_id'], ['Posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['voter_id'], ['Users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'voter_id')
    )
    op.add_column('Posts', sa.Column('User_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('post_users_fk'), 'Posts', type_='foreignkey')
    op.create_foreign_key(None, 'Posts', 'Users', ['User_id'], ['id'], ondelete='CASCADE')
    op.drop_column('Posts', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Posts', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Posts', type_='foreignkey')
    op.create_foreign_key(op.f('post_users_fk'), 'Posts', 'Users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('Posts', 'User_id')
    op.drop_table('Votes')
    # ### end Alembic commands ###
